agent_horizon_s: 1.75
radius_m: 9.0
num_semantic_classes: 20
min_distance_m: 0.5
max_distance_m: 2.5
distance_bins: 30
min_correspondences: 10
min_inliers: 7
agent:
    min_score: 0.07
    type: "L1"
object:
    min_score: 0.2
    min_registration_score: 0.4
    type: "L1"
places:
    min_score: 0.2
    min_registration_score: 1.5 # disables registration
    type: "L1"
