pgmo:
    horizon: 5.0
    output_mesh_resolution: 0.04
    compression_method: 1  # voxblox
    robot_id: 0
    d_graph_resolution: 1.0
    voxblox_queue_size: 1
enable_rooms: true
building_color: [0.572, 0.204, 0.922]
room_finder:
    min_dilation_m: 0.43
    max_dilation_m: 1.2
    num_steps: 10
    min_component_size: 10
    room_vote_min_overlap: 0.1
    min_room_size: 1
    max_kmeans_iters: 5
    do_spectral_clustering: true
    use_sparse_eigen_decomp: true
    sparse_decomp_tolerance: 1.0e-2
    max_modularity_iters: 5
    modularity_gamma: 1.0
    clustering_mode: "MODULARITY"
