odom_trans_threshold: 0.05
odom_rot_threshold: 0.01
pcm_trans_threshold: -1
pcm_rot_threshold: -1
lm_diagonal_damping: true
gnc_alpha: 0.99
gnc_max_iterations: 100
gnc_mu_step: 1.6
gnc_cost_tolerance: 1.0e-05
gnc_weight_tolerance: 1.0e-04
odom_trans: 1.0e-02
odom_rot: 1.0e-04
loop_close_trans: 5.0e-02
loop_close_rot: 5.0e-04
use_height_bound: false
use_height_prior: true
heights:
    - {start: 0, stop: 4000, inc: 1, lower: -0.2, upper: 0.2, mu: 1.0e-2}
    - {start: 7300, stop: 10000, inc: 1, lower: -1.0, upper: 1.0, mu: 1.0e-2}
    - {start: 4200, stop: 7150, inc: 1, lower: 2.0, upper: 3.0, mu: 1.0e-2}
