pgmo:
    horizon: 100.0
    output_mesh_resolution: 0.04
    graph_compression_method: 1  # voxblox
    full_compression_method: 2  # voxel clearing
    robot_id: 0
    d_graph_resolution: 2.5
    voxblox_queue_size: 1
building_color: [0.572, 0.204, 0.922]
mesh_queue_size: 10