---
odom_trans_threshold: 0.05
odom_rot_threshold: 0.01
pcm_trans_threshold: -1
pcm_rot_threshold: -1
lm_diagonal_damping: true
gnc_alpha: 0.999
gnc_max_iterations: 100
gnc_mu_step: 1.6
gnc_cost_tolerance: 1.0e-05
gnc_weight_tolerance: 1.0e-04
odom_trans: 1.0e-02
odom_rot: 1.0e-04
loop_close_trans: 5.0e-02
loop_close_rot: 5.0e-04
heights:
  - {start: 0, stop: 4150, inc: 1, height: 0.0, variance: 1.0e-2, default_variance: 100.0}
  - {start: 4250, stop: 7150, inc: 1, height: 2.6, variance: 1.0e-2, default_variance: 100.0}
  - {start: 7300, stop: 8500, inc: 1, height: 0.0, variance: 1.0e-2, default_variance: 100.0}
manual_lc_var: 0.1
#manual_loop_closures:
  #- {index1: 2282, index2: 2549}
  #- {index1: 2715, index2: 3904}
  #- {index1: 2715, index2: 4110}
  #- {index1: 2947, index2: 3661}
  #- {index1: 2996, index2: 3427}

