---
odom_trans_threshold: 0.05
odom_rot_threshold: 0.01
pcm_trans_threshold: -1
pcm_rot_threshold: -1
lm_diagonal_damping: true
gnc_alpha: 0.999
gnc_max_iterations: 100
gnc_mu_step: 1.6
gnc_cost_tolerance: 1.0e-05
gnc_weight_tolerance: 1.0e-04
odom_trans: 5.0e-02
odom_rot: 5.0e-03
loop_close_trans: 5.0e-02
loop_close_rot: 5.0e-03
heights:
  - {start: 0, stop: 3320, inc: 1, height: 0.0, variance: 1.0, default_variance: 10000.0}
  #- {start: 3720, stop: 5650, inc: 1, height: 6.0, variance: 10.0, default_variance: 10000.0}
  #- {start: 6075, stop: 7150, inc: 1, height: 0.0, variance: 1.0, default_variance: 100.0}
manual_lc_var: 0.5
manual_loop_closures:
  - {index1: 0, index2: 7145}
  #- {index1: 2715, index2: 3904}
  #- {index1: 2715, index2: 4110}
  #- {index1: 2947, index2: 3661}
  #- {index1: 2996, index2: 3427}

